### ISSUE TITLE
MouseV1 Conversion

### ISSUE THREAD

**Issue by alessandratrapani** [catalystneuro/mousev1-to-nwb#1]
This is to organize the conversion. 
Some general resources.

1. [analysis code](https://github.com/willyh101/analysis)
2. [Probing inter-areal computations with a cellular resolution two-photon holographic mesoscope](https://www.biorxiv.org/content/10.1101/2022.03.20.485047v1)

TO-DO:

- [x] Add conversion notes. (https://github.com/catalystneuro/mousev1-to-nwb/pull/2)
- [x] Add 2p Ca2+ imaging extractor (ScanImage).(#4 )
- [x] Add 2p Ca2+ imaging interfaces (#5 )
- [x] Add imaging metadata (#8)
- [x] Add processed Suite2P. (#6)
- [x] Implement ndx-patterned-ogen https://github.com/catalystneuro/ndx-patterned-ogen/pull/2
- [x] Add holographic stimulus (#7)
- [x] Add annotated behavioral events  (#12)
- [x] Add session and subject metadata (#9)
- [x] Run a stub conversion for the data we have and use the inspector. (#11)
- [x] Run stubs (#13)
- [x] Run validation using inspector
- [x] Run full conversion
- [x] Run validation.
- [x] Create demos notebook (#15)
- [x] Upload to dandi
- [x] Set the requirements. (#16)
- [x] Modify the documentation in the readme. (#15)
